### ISSUE TITLE
Enable selective sync

### ISSUE THREAD

**Issue by cwlbraa** [k14s/vendir#5]
Today on cf-for-k8s, when I `vendir sync --use-directory` to replace some remote code with local dev copies, it takes 30s to redownload all the dependencies. I really only need to move the files from the one directory. Could this be made faster?

**Comment by cppforlife** [comment]
@cwlbraa good point. cf-for-k8s definitely got beefier.

**Comment by cppforlife** [comment]
covered by https://github.com/k14s/vendir/releases/tag/v0.7.0. 

eg `vendir sync -d config/_ytt_lib/github.com/cloudfoundry/cf-k8s-networking=~/workspace/cf-k8s-networking` to just touch that directory.
